[package]
name = 'aptos-my-counter'
version = '1.0.0'

[addresses]
publisher='_'

[dev-addresses]
publisher='0xC0FFEE'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
